# These are supported funding model platforms

github: [VAIBHAVSING] # GitHub Sponsors
patreon: # dev8dev # Patreon username 
open_collective: # dev8dev # Open Collective username
ko_fi: # dev8dev # Ko-fi username
tidelift: # npm/dev8dev # Tidelift platform-name/package-name
community_bridge: # dev8dev # Community Bridge project name
liberapay: # dev8dev # Liberapay username
issuehunt: # dev8dev # IssueHunt username
custom: ['https://dev8.dev/sponsor', 'https://dev8.dev/donate'] # Custom sponsorship URLs
