name: Quick Check

on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PNPM_VERSION: 9
  NODE_VERSION: 20

jobs:
  quick-check:
    name: Quick Lint & Build Check
    runs-on: ubuntu-latest
    
    # Add environment variables needed for the build
    env:
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'fallback-secret-for-ci' }}
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://test:test@localhost:5432/testdb
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || 'test-client-id' }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || 'test-client-secret' }}
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID || 'test-github-id' }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET || 'test-github-secret' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "pnpm-cache-dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm-cache-dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Check TypeScript types
        run: pnpm check-types

      - name: Test build
        run: pnpm build
